// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ngobvhrfqblofacuqsru.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5nb2J2aHJmcWJsb2ZhY3Vxc3J1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE5OTQ1NTYsImV4cCI6MjA2NzU3MDU1Nn0.F91fkH235VQY8kE4TPQZY0AI2RzYqG9e20EydPVL0Ms";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});